"""ACP v2 schema definitions.

All v2 protocol types. Import v2 types from here:
    from acp_v2.schema import SessionUpdate, StateUpdate, ToolCallUpdate
"""

from acp_v2.schema._unset import _UNSET, UnsetType, is_unset
from acp_v2.schema.capabilities import (
    AuthCapabilities,
    Capabilities,
    McpCapabilities,
    PromptCapabilities,
    SessionCapabilities,
)
from acp_v2.schema.client_requests import (
    CancelNotification,
    CloseSessionRequest,
    InitializeRequest,
    ListSessionsRequest,  # noqa: F401
    LoadSessionRequest,
    LoginAuthRequest,
    LogoutAuthRequest,
    NewSessionRequest,
    PromptRequest,
    SetSessionConfigOptionRequest,
)
from acp_v2.schema.client_responses import (
    CloseSessionResponse,
    ForkSessionResponse,
    InitializeResponse,
    ListSessionsResponse,  # noqa: F401
    LoadSessionResponse,
    LoginAuthResponse,
    LogoutAuthResponse,
    NewSessionResponse,
    PromptResponse,
    ResumeSessionResponse,
    SetSessionConfigOptionResponse,
    StopReason,
)
from acp_v2.schema.messages import AgentMethod, ClientMethod
from acp_v2.schema.notifications import (
    AgentNotification,
    CancelNotification as CancelNotif,
    ClientNotification,
    ExtNotification,
    SessionNotification,
)
from acp_v2.schema.session_updates import (
    AgentMessage,
    AgentMessageChunk,
    AgentThought,
    AgentThoughtChunk,
    AvailableCommandsUpdate,
    ConfigOptionUpdate,
    Cost,
    PlanItems,
    PlanUpdate,
    SessionInfoUpdate,
    SessionState,
    SessionUpdate,
    StateUpdate,
    ToolCallContentChunk,
    ToolCallStatus,
    ToolCallUpdate,
    Usage,
    UsageUpdate,
    UserMessage,
    UserMessageChunk,
)

__all__ = [
    "AgentMessage",
    "AgentMessageChunk",
    "AgentMethod",
    "AgentNotification",
    "AgentThought",
    "AgentThoughtChunk",
    "AuthCapabilities",
    "AvailableCommandsUpdate",
    "CancelNotif",
    "CancelNotification",
    "Capabilities",
    "ClientMethod",
    "ClientNotification",
    "CloseSessionRequest",
    "CloseSessionResponse",
    "ConfigOptionUpdate",
    "Cost",
    "ExtNotification",
    "ForkSessionResponse",
    "InitializeRequest",
    "InitializeResponse",
    "LoadSessionRequest",
    "LoadSessionResponse",
    "LoginAuthRequest",
    "LoginAuthResponse",
    "LogoutAuthRequest",
    "LogoutAuthResponse",
    "McpCapabilities",
    "NewSessionRequest",
    "NewSessionResponse",
    "PlanItems",
    "PlanUpdate",
    "PromptCapabilities",
    "PromptRequest",
    "PromptResponse",
    "ResumeSessionResponse",
    "SessionCapabilities",
    "SessionInfoUpdate",
    "SessionNotification",
    "SessionState",
    "SessionUpdate",
    "SetSessionConfigOptionRequest",
    "SetSessionConfigOptionResponse",
    "StateUpdate",
    "StopReason",
    "ToolCallContentChunk",
    "ToolCallStatus",
    "ToolCallUpdate",
    "UnsetType",
    "Usage",
    "UsageUpdate",
    "UserMessage",
    "UserMessageChunk",
    "_UNSET",
    "is_unset",
]
