id = "wolfharness"
name = "AgentPool"
description = "Pydantic-AI based Multi-Agent Framework with YAML-based Agents, Teams, Workflows & Extended ACP / AGUI integration"
version = "1.15.12"
schema_version = 1
authors = ["Philipp Temminghoff"]
repository = "https://github.com/phil65/wolfharness"

[agent_servers.wolfharness]
name = "AgentPool"
icon = "./icons/wolfharness.svg"

[agent_servers.wolfharness.targets.darwin-aarch64]
archive = "https://github.com/phil65/wolfharness/releases/download/v2.9.5/wolfharness-darwin-aarch64-1.15.12.zip"
cmd = "./wolfharness"
args = ["serve-acp"]

[agent_servers.wolfharness.targets.darwin-x86_64]
archive = "https://github.com/phil65/wolfharness/releases/download/v2.9.5/wolfharness-darwin-x86_64-1.15.12.zip"
cmd = "./wolfharness"
args = ["serve-acp"]

# [agent_servers.wolfharness.targets.linux-aarch64]
# archive = "https://github.com/phil65/wolfharness/releases/download/v2.9.5/wolfharness-linux-aarch64-1.15.12.zip"
# cmd = "./wolfharness"
# args = ["serve-acp"]

[agent_servers.wolfharness.targets.linux-x86_64]
archive = "https://github.com/phil65/wolfharness/releases/download/v2.9.5/wolfharness-linux-x86_64-1.15.12.zip"
cmd = "./wolfharness"
args = ["serve-acp"]

# [agent_servers.wolfharness.targets.windows-aarch64]
# archive = "https://github.com/phil65/wolfharness/releases/download/v2.9.5/wolfharness-windows-aarch64-1.15.12.zip"
# cmd = "./wolfharness.exe"
# args = ["serve-acp"]

[agent_servers.wolfharness.targets.windows-x86_64]
archive = "https://github.com/phil65/wolfharness/releases/download/v2.9.5/wolfharness-windows-x86_64-1.15.12.zip"
cmd = "./wolfharness.exe"
args = ["serve-acp"]
